services:
  backend:
    image: shadysloth/examapi
    ports:
      - 6001:8080
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    depends_on:
      db-postgres:
        condition: service_healthy
  db-postgres:
    image: postgres:15
    restart: always
    shm_size: 128mb
    hostname: db-postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_user
      - db_password
    ports:
      - 6002:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 20

secrets:
  db_user:
    file: db_user.txt
  db_password:
    file: db_password.txt